[project]
name = "lick-template"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "lick==0.7.3",
    "nonos>=0.19.0",
    "numpy==1.26.4",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
]
